PREFIX = /usr
INSTALL_INC  = $$INSTALL_ROOT$$PREFIX/include/
INSTALL_BIN  = $$INSTALL_ROOT$$PREFIX/bin/
INSTALL_LIB  = $$INSTALL_ROOT$$PREFIX/lib/
INSTALL_DATA = $$INSTALL_ROOT$$PREFIX/share/
INSTALL_DOC  = $$INSTALL_DATA/doc/

CONFIG += meego-com

CONFIG(meego-com) {
    DBUS_ROOT = com.meego
    DEFINES += MEEGO_COM
} else {
    DBUS_ROOT = com.nokia
}

DBUS_SERVICE   = $${DBUS_ROOT}.ShareUi
DBUS_INTERFACE = $${DBUS_ROOT}.ShareUiInterface

DEFINES += DBUS_SERVICE=$$DBUS_SERVICE
