######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 28 10:16:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += shareuiinterface-maemo-meegotouch

# Input
SOURCES += Share-UI-Example.cpp
